-- Spanyard schema
-- Run this in Supabase SQL editor

create schema if not exists spanyard;

-- 1000 most common Spanish words
create table if not exists spanyard.words (
  id          serial primary key,
  rank        integer unique not null,
  spanish     text not null,
  english     text not null,
  pos         text  -- part of speech
);

-- Single-user progress tracking
create table if not exists spanyard.user_words (
  id               serial primary key,
  word_id          integer not null references spanyard.words(id) on delete cascade,
  box              integer not null default 1 check (box between 1 and 5),
  next_review_at   timestamptz not null default now(),
  last_reviewed_at timestamptz,
  unique (word_id)
);

-- JIT sentence cache (generated by Claude)
create table if not exists spanyard.sentences (
  id         serial primary key,
  word_id    integer not null references spanyard.words(id) on delete cascade unique,
  spanish    text not null,
  english    text not null,
  cloze      text not null,  -- spanish with {{word}} placeholder
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists user_words_next_review_idx on spanyard.user_words (next_review_at);
create index if not exists user_words_box_idx on spanyard.user_words (box);

-- RLS: Disable for single-user app (enable if adding auth later)
alter table spanyard.words enable row level security;
alter table spanyard.user_words enable row level security;
alter table spanyard.sentences enable row level security;

-- Allow all access (single-user, anon key)
create policy "allow all words"      on spanyard.words      for all using (true) with check (true);
create policy "allow all user_words" on spanyard.user_words for all using (true) with check (true);
create policy "allow all sentences"  on spanyard.sentences  for all using (true) with check (true);
